name: 'Auto Release Notes'
description: 'Updates PR content with features & chores'
branding:
  icon: 'play-circle'
  color: 'red'
inputs:
  github_token:
    description: 'Github Token'
    required: true
  feature_commit_pattern:
    description: 'Feature commit pattern'
    required: true
    default: 'JIRA-'
  description_template:
    description: 'This is a description template use {{feature_commits}} to replace it by list of commits matched using feature_commit_pattern and {{chores_commits}} will be replace by commit description list not matched feature_commit_pattern.'
    required: false
  description_template_filepath:
    description: 'If you need to use more complex template you can use MD file. Use {{feature_commits}} in the template to replace it with list of commits matched using feature_commit_pattern and {{chores_commits}} will be replace by commit description list not matched feature_commit_pattern. This will overwrite description_template. If file not exist will fallback to description_template.'
    required: false
  title_template:
    description: 'This is a pattern for PR name. {{date}} will be replace by D MM'
    required: false
  ticket_management:
    description: 'IF you use ticket management you can pass it here and job will replace feature commits with JIRA issue titles. Possible options: jira'
    required: false
  jira_username:
    description: 'If you are using JIRA as your ticket management system you can have add username and password so instead of commits release notes will have issue titles'
    required: false
  jira_password:
    description: 'If you are using JIRA as your ticket management system you can have add username and password so instead of commits release notes will have issue titles'
    required: false
  jira_url:
    description: 'If you are using JIRA as your ticket management system you can add JIRA url so job will connect and try to check all linked comits. Instead of commits messages it will display JIRA titles'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
